FROM golang:alpine as builder
ENV GOBIN /go/bin

RUN mkdir /app
RUN mkdir /go/src/app

WORKDIR /go/src/app

RUN apk add --no-cache git
RUN go get -u github.com/golang/dep/...

COPY . /go/src/app
RUN dep ensure
RUN go build -o /app/main

FROM alpine
ARG DB_HOST
ARG PORT
ARG NSQD_TCP_URL
ARG NSQLOOKUP_HTTP_URL
ARG PUBLISHED_HOSTNAME
ARG PUBLISHED_PORT
ARG CLIENT_ID
ARG CLIENT_SECRET
ARG API_GATEWAY_HOST
ARG API_GATEWAY_PORT
ARG API_GATEWAY_PATH

ENV DB_HOST=$DB_HOST
ENV PORT=$PORT
ENV NSQD_TCP_URL=$NSQD_TCP_URL
ENV NSQLOOKUP_HTTP_URL=$NSQLOOKUP_HTTP_URL
ENV PUBLISHED_HOSTNAME=$PUBLISHED_HOSTNAME
ENV PUBLISHED_PORT=$PUBLISHED_PORT
ENV CLIENT_ID=$CLIENT_ID
ENV CLIENT_SECRET=$CLIENT_SECRET
ENV API_GATEWAY_HOST=$API_GATEWAY_HOST
ENV API_GATEWAY_PORT=$API_GATEWAY_PORT
ENV API_GATEWAY_PATH=$API_GATEWAY_PA

EXPOSE $PORT

WORKDIR /app
COPY --from=builder /app/main /app/

ENTRYPOINT ["/app/main"]